[build]
  command = "yarn build"

[dev]
  command = "yarn start"
  publish = "public/"
  targetPort = 3000
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/effection/:splat"

[[redirects]]
  force = true
  from = "/effection/api/*"
  status = 200
  to = "https://frontside.com/tools/:splat"
