[build]
  command = "yarn build"
  publish = "public/"

[dev]
  command = "yarn start"
  publish = "public/"
  targetPort = 3000
  framework = "#custom"

[[redirects]]
  force = true
  from = "/effection/api/*"
  status = 200
  to = "https://effection-api.netlify.app/:splat"
    # todo: this needs to be updated to https://v2--eeffection-api.netlify.app

[[redirects]]
  from = "/*"
  to = "/effection/:splat"
